### PR TITLE
Use JSON file for sample LDAP names

### PR DESCRIPTION
**Pull request by PVince81**
Better than a PHP-serialized uneditable file

@owncloud/ldap @owncloud/qa

### CODE REVIEW

**Comment by jvillafanez** [comment]
I suggest to check the performance first. I expect the json implementation will be slower, but if it's by far, we might want to keep the PHP implementation (unless we don't care at all about the speed).

**Comment by PVince81** [comment]
@jvillafanez this is only testing code (not core code), the performance doesn't matter much here.
I didn't see any big difference between the two.

This is mainly just a sample names DB that can be randomly used to creating dummy users.

**Comment by PVince81** [comment]
the real reason why I wanted a JSON file: I wanted to be able to strip the accents and umlauts because for some reason on my local instance any name with accents fail. But when I did that on the serialized file PHP was unhappy about string lengths.

**Comment by jvillafanez** [comment]
ok, fair enough 👍

**Comment by PVince81** [comment]
(I do appreciate your care for performance, keep up to good work :wink:)

**Pull request merged**
