### PR TITLE
[Update server] Push 8.2.11 9.0.9 9.1.5 10.0.0rc1 to the beta channel

### PR DESCRIPTION
**Pull request by VicDeo**

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
@VicDeo we also need those 9.1.5, 9.0.9 and 8.2.11 on the stable channels

**Comment by VicDeo** [comment]
@PVince81 Let's push this first for smoke testing. 
I'm preparing single PR for all the other channel.

**Comment by VicDeo** [comment]
@crrodriguez could you please deploy it to the server?

**Comment by crrodriguez** [comment]
long ago deployed, please close (I can't)

**Comment by VicDeo** [comment]
@crrodriguez What was merged can't be closed. Just because it's not an issue but a pull request.

**Pull request merged**
