### PR TITLE
Make PHP_OS uppercase before checking for Windows

### PR DESCRIPTION
**Pull request by RealRancor**
As discussed in https://github.com/owncloud/core/pull/26316

> According to:
>
>https://gist.github.com/asika32764/90e49a82c124858c9e1a
>
>http://stackoverflow.com/questions/738823/possible-values-for-php-os
>
>there are three possible values on Windows:
>
>WIN32
>WINNT
>Windows

### CODE REVIEW

**Comment by RealRancor** [comment]
@PVince81 @DeepDiver1975 Also something to merge here as its just the same check like in the merged https://github.com/owncloud/core/issues/26316

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
@crrodriguez can you deploy setup-owncloud.php ?

cc @jnweiger

**Comment by RealRancor** [comment]
Be aware that the setup-owncloud.php is currently checking for PHP 5.6 and not 5.4

**Pull request merged**
