### PR TITLE
Push 10.0.8 to all channels

### PR DESCRIPTION
**Pull request by VicDeo**
Make 10.0.8 available for web update

### CODE REVIEW

**Comment by davitol** [comment]
Looks like LDAP app is uninstalled after the update. 

**Testing environment**
oC 10.0.5 + LDAP enabled + Encryption enabled + updater server with this PR. Admin user updates to 10.0.8 via stable channel 

owncloud.log :
```
{"reqId":"SF2RwVKcGY8GK3V5YppH","level":3,"time":"2018-05-03T06:24:22+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"\/index.php\/occ\/status","message":"array_shift() expects parameter 1 to be array, null given at \/opt\/owncloud\/lib\/composer\/symfony\/console\/Input\/ArgvInput.php#57"}
{"reqId":"SF2RwVKcGY8GK3V5YppH","level":3,"time":"2018-05-03T06:24:22+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"\/index.php\/occ\/status","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/lib\/composer\/symfony\/console\/Input\/ArgvInput.php#264"}
{"reqId":"ItITuh4oSorTEpIVGSQx","level":3,"time":"2018-05-03T06:24:22+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"\/index.php\/occ\/config:list","message":"Undefined index: argv at \/opt\/owncloud\/lib\/composer\/symfony\/console\/Input\/ArgvInput.php#53"}
{"reqId":"ItITuh4oSorTEpIVGSQx","level":3,"time":"2018-05-03T06:24:22+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"\/index.php\/occ\/config:list","message":"array_shift() expects parameter 1 to be array, null given at \/opt\/owncloud\/lib\/composer\/symfony\/console\/Input\/ArgvInput.php#57"}
{"reqId":"ItITuh4oSorTEpIVGSQx","level":3,"time":"2018-05-03T06:24:22+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"\/index.php\/occ\/config:list","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/lib\/composer\/symfony\/console\/Input\/ArgvInput.php#264"}
{"reqId":"PlmDi7F8FoUFbOWAPtxR","level":3,"time":"2018-05-03T06:24:25+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"\/index.php\/occ\/integrity:check-core","message":"Undefined index: argv at \/opt\/owncloud\/lib\/composer\/symfony\/console\/Input\/ArgvInput.php#53"}
{"reqId":"PlmDi7F8FoUFbOWAPtxR","level":3,"time":"2018-05-03T06:24:25+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"\/index.php\/occ\/integrity:check-core","message":"array_shift() expects parameter 1 to be array, null given at \/opt\/owncloud\/lib\/composer\/symfony\/console\/Input\/ArgvInput.php#57"}
{"reqId":"PlmDi7F8FoUFbOWAPtxR","level":3,"time":"2018-05-03T06:24:25+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"\/index.php\/occ\/integrity:check-core","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/lib\/composer\/symfony\/console\/Input\/ArgvInput.php#264"}
{"reqId":"KUVUBXGkJum2xsEwEZEO","level":2,"time":"2018-05-03T06:27:29+00:00","remoteAddr":"85.57.168.79","user":"--","app":"core","method":"POST","url":"\/index.php\/login","message":"Login failed: 'aaliyah_adams' (Remote IP: '85.57.168.79')"}
{"reqId":"WHhXImu4G6HwXM3cAYUQ","level":2,"time":"2018-05-03T06:27:38+00:00","remoteAddr":"85.57.168.79","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=aaliyah_adams","message":"Login failed: 'aaliyah_adams' (Remote IP: '85.57.168.79')"}
```

any clue @VicDeo

**Comment by VicDeo** [comment]
@davitol yet another updater bug. 
Pushed https://github.com/owncloud/updater/pull/469 fixing it

**Comment by davitol** [comment]
@crrodriguez Please deploy this PR. Backports for the fix in updater stable10 branch and the Central post can be done later

**Comment by crrodriguez** [comment]
@davitol done right now.

**Pull request merged**
