### PR TITLE
Add PHPUnit 6.0.x compatibility

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes https://github.com/owncloud/administration/issues/115

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
What? Where is phpunit 6.0 coming from?

Properly setting up composer.json will ensure that the correct version of phpunit is pulled in.
It we really want to use phpunit 6.0 - we better properly migrate the test and no use this hack

**Comment by VicDeo** [comment]
@DeepDiver1975 it comes from Travis env for PHP 7 and phpunit.de :)
6.0 is a current stable for over a month.

That's why all repos with PHP7 in matrix are failing on new PRs (e.g. files_antivirus)

**Comment by DeepDiver1975** [comment]
I know but we shall use the version as specified in composer json in core

**Pull request merged**
