### PR TITLE
Updater-server: push latest 8.1.12 to all channels

### PR DESCRIPTION
**Pull request by VicDeo**
Release 8.1.12 for web updater

### CODE REVIEW

**Comment by PVince81** [comment]
@davitol please test

**Comment by PVince81** [comment]
@VicDeo Can you take of the other updates too ?

**Comment by davitol** [comment]
:+1: WFM

**Comment by davitol** [comment]
Testing this PR I missed this stuff in daily:

```
	'daily' => [
3 months ago @PVince81 Make update server public 	
		'9.2' => [
			'downloadUrl' => 'https://download.owncloud.org/community/owncloud-daily-master.zip',
			'web' => 'https://doc.owncloud.org/server/9.2/admin_manual/maintenance/upgrade.html',
```
I guess it should be 10.0 oC version instead of 9.2. @VicDeo

**Pull request merged**
