### PR TITLE
Push 10.0.8RC3 to the beta channel

### PR DESCRIPTION
**Pull request by VicDeo**
Allow update to 10.0.8RC3 via beta channel

### CODE REVIEW

**Comment by VicDeo** [comment]
Updated to RC3

**Comment by SergioBertolinSG** [comment]
It works fine updating from 10.0.7 to 10.0.8.

Using 9.1.8 I cannot see 10.0.8RC3 in the beta channel:

screen shot 2018-04-20 at 10 35 19

**Comment by VicDeo** [comment]
@SergioBertolinSG 
It could be a caching issue if a updater server url was updated after switching the channel to beta
just switch the channel to anything else and then back to beta to clean the cache.

**Comment by SergioBertolinSG** [comment]
That didn't help. I changed the browser as well and it didn't help either.

**Comment by PVince81** [comment]
obsolete... let's prepare PR for 10.0.8

**Pull request closed without merging**
