### PR TITLE
Add 10.0.3rc1 to beta channel

### PR DESCRIPTION
**Pull request by PVince81**
Quick tests on beta channel:
- [x] update 10.0.2 -> 10.0.3rc1
- [x] update 9.1.6 -> 10.0.3rc1
- [x] ~~update 9.0.10 -> 10.0.3beta~~ 🚫 not possible, but we can make it possible for 9.0.11: https://github.com/owncloud/updater/issues/435
- [x] ~~update 8.2.11 -> 10.0.3beta~~ => not possible, updater app refuses to skip

@davitol @VicDeo 

@felixboehm FYI, at this point I'd like to make the web updater update directly to 10.0.3 when possible

### CODE REVIEW

**Comment by PVince81** [comment]
Turns out you cannot update from 8.2.11 or 9.0.10 to 10.0.3 with the updater, because the updater itself has a version check and disallows skipping major updates. This means we will not be able to provide this update path because 8.2.11 is EOL.

However if we choose to, we could fix the updater in the upcoming 9.0.11 to allow upgrading directly to 10.0 or later versions. Such updates will be possible in the future anyway. Raised here: https://github.com/owncloud/updater/issues/435

**Comment by PVince81** [comment]
I've reverted the commit for the major version skipping updates.

All that remains now is 10.0.x to 10.0.3beta updates

**Comment by felixboehm** [comment]
Clarifying:
- update 8.2 -> 10 works, but the web updater does not support the update path.
- manual update with tarball / packages works directly.

**Comment by PVince81** [comment]
Let's not invest time in making 9.0.11->10.0.3 work with the updater. The updater already allows for iterative updates so people with 9.0.11 can just go to 9.1 first then 10.0.

So this PR's focus is now only 10.0.x -> 10.0.3

**Comment by PVince81** [comment]
minor integrity check error: https://github.com/owncloud/updater/issues/436

**Comment by VicDeo** [comment]
@PVince81 8.2 to 10 is not possible indeed, but 9.0 to 10.0 should work. 
At least I see nothing that  blocks this update path.

**Comment by PVince81** [comment]
We decided to not support 9.0 -> 10.0.3beta with the web update as it means more time needs to be invested in testing this update path. It's not worth it considering that people can already iterate with the web updater and reach 10.0.3 as well.

**Comment by VicDeo** [comment]
@PVince81 @davitol link/tests are updated to 10.0.3rc1

**Comment by VicDeo** [comment]
@crrodriguez please deploy it

**Comment by PVince81** [comment]
thanks

**Comment by crrodriguez** [comment]
deployed.

**Pull request merged**
