### PR TITLE
Allow 9.1.x to 9.1.4

### PR DESCRIPTION
**Pull request by VicDeo**
Unlock update to 9.1.4 for 9.1.x

### CODE REVIEW

**Comment by davitol** [comment]
@VicDeo updating from 9.1.3 to 9.1.4.  integrity check throws an error:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- updater/.gitignore

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [updater/.gitignore] => Array
                        (
                            [expected] => 
                            [current] => 7c017a81ca97f082b0d97869336cd41ad0d02e67de4865e33ca031775dc9ea5e9e7f024a4fa8016e58f29e7c4fd90d1633944ffbab37ee4c4ff739443c8d059c
                        )

                )

        )

)
```

**Comment by davitol** [comment]
@VicDeo root@02bcd0be5fdc:/opt/owncloud/updater# ls -al

```
drwxr-xr-x  7 www-data www-data  4096 Mar  3 12:19 .
drwxr-xr-x 15 www-data www-data  4096 Mar  3 12:17 ..
drwxr-xr-x  3 www-data www-data  4096 Mar  3 12:19 app
-rw-r--r--  1 www-data www-data  1442 Mar  3 12:19 application.php
-rw-r--r--  1 www-data www-data   187 Mar  3 12:19 box.json
-rw-r--r--  1 www-data www-data   434 Mar  3 12:19 composer.json
-rw-r--r--  1 www-data www-data 24380 Mar  3 12:19 composer.lock
-rw-r--r--  1 www-data www-data  1737 Mar  3 12:19 CONTRIBUTING.md
-rw-r--r--  1 www-data www-data 34520 Mar  3 12:19 COPYING-AGPL
-rw-r--r--  1 www-data www-data   194 Dec 12 17:42 .gitignore
-rw-r--r--  1 www-data www-data   974 Mar  3 12:19 index.php
drwxr-xr-x  2 www-data www-data  4096 Dec 12 17:42 nbproject
drwxr-xr-x  5 www-data www-data  4096 Mar  3 12:19 pub
-rw-r--r--  1 www-data www-data   586 Mar  3 12:19 README.md
-rw-r--r--  1 www-data www-data   201 Mar  3 12:19 .scrutinizer.yml
drwxr-xr-x 10 www-data www-data  4096 Mar  3 12:19 src
-rw-r--r--  1 www-data www-data   606 Mar  3 12:19 .travis.yml
drwxr-xr-x 11 www-data www-data  4096 Mar  3 12:19 vendor
```
Does some of these files are left over?

**Comment by davitol** [comment]
Same behaviour updating via CLI from 9.1.2. to 9.1.4

**Comment by VicDeo** [comment]
yes. `updater/.gitignore` wws included into 9.1.2 but not in 9.1.4
It seems to be a bug in self-update process.

**Comment by davitol** [comment]
@VicDeo updating from 9.1.4 to Master:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- updater/nbproject/project.xml
		- updater/nbproject/project.properties

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [updater/nbproject/project.xml] => Array
                        (
                            [expected] => 
                            [current] => a5dd5681c52d4276b6b77073d2f3926a00c377df5d2245ae19862677c994f41aafd12e04f67b9b555b1f2accd69799371f156c16a4f0522ce6ead68f04b051ff
                        )

                    [updater/nbproject/project.properties] => Array
                        (
                            [expected] => 
                            [current] => aa32bf4a6e266245551b1edc03d2846f405a63518e1dee11e0b151d4f16d263a371cb4f1fbe2aaf1ee6ee7d978f3a978d2b3e5b897a93a9429d246cb4109c1c3
                        )

                )

        )

)
```

**Comment by PVince81** [comment]
Let's publish this and inform people that they need to manually delete this file.

**Comment by PVince81** [comment]
@crrodriguez please deploy

**Comment by crrodriguez** [comment]
done

**Pull request merged**
