### PR TITLE
Push 10.1 to all channels

### PR DESCRIPTION
**Pull request by VicDeo**
Allow web update to 10.1

### CODE REVIEW

**Comment by davitol** [comment]
@VicDeo Updating from 10.0.10 to 10.1

Integrity check error

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- ocm-provider/index.php

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [ocm-provider/index.php] => Array
                        (
                            [expected] => 0c640fe229b0d25f3c291e368ad5a337df4c84e97d1ff750f6db6fa548d64f7caf78dd6b9ad23aa68fccdb747a380f399250a5cf1535b8029f09ea02d8c777ad
                            [current] => 
                        )

                )

        )

)
```

**Comment by VicDeo** [comment]
ah, crap...

**Comment by PVince81** [comment]
@VicDeo can you fix the updater then, so it will be ready in 10.2 ?

**Comment by VicDeo** [comment]
@PVince81 sure

**Comment by PVince81** [comment]
raised https://github.com/owncloud/updater/issues/495

**Comment by PVince81** [comment]
maybe we only publish 10.1 on the beta channels then for those who aren't scared of errors ?

**Comment by PVince81** [comment]
abandoning for now. to be done for 10.2

**Pull request closed without merging**
