### PR TITLE
Push 10.0.2 to all channels

### PR DESCRIPTION
**Pull request by VicDeo**
resurrecting 10.0.2-related part of #129

### CODE REVIEW

**Comment by davitol** [comment]
**Test results**

webUI

- [ ] Update from 9.1.6 to 10.0.2 via webUI
- [ ] Update from 10.0.0 to 10.0.2 via webUI
- [ ] Update from 10.0.1 to 10.0.2 via webUI

CLI

- [ ] Update from 9.1.6 to 10.0.2 via CLI
- [ ] Update from 10.0.0 to 10.0.2 via CLI
- [ ] Update from 10.0.1 to 10.0.2 via CLI

**Comment by VicDeo** [comment]
@davitol I've added integration test fror 10.0.1 and it is passed. https://github.com/owncloud/administration/pull/132/commits/5e6d6a4772f5afcdcf291cbb7eb88f620f9e8e6b 
May I have a look at your update server?

**Comment by davitol** [comment]
It keeps failing for me with the updated patch https://central.owncloud.org/t/patches-for-known-update-issues-from-versions-10-0-0-10-0-2-updated-on-june-12/7911

**Comment by davitol** [comment]
@VicDeo with the update 13th June https://central.owncloud.org/t/patches-for-known-update-issues-from-versions-10-0-0-10-0-2-updated-on-june-13/7911 10.0.0 to 10.0.2 updates went fine now via daily channel, but I never get the stable channel update offered.

**Comment by davitol** [comment]
**Test results**

webUI

- ✅    Update from 9.1.6 to 10.0.2 via webUI --> This PR is not merged yet: https://github.com/owncloud/updater/issues/428
- ✅   Update from 10.0.0 to 10.0.2 via webUI https://github.com/owncloud/updater/issues/429 --> Hot fix in https://central.owncloud.org/t/patches-for-known-update-issues-from-versions-10-0-0-10-0-2-updated-on-june-13/7911
- ✅   Update from 10.0.1 to 10.0.2 via webUI

CLI

- ✅  Update from 9.1.6 to 10.0.2 via CLI
- ✅  Update from 10.0.0 to 10.0.2 via CLI --> https://github.com/owncloud/updater/issues/429 --> Hot fix in https://central.owncloud.org/t/patches-for-known-update-issues-from-versions-10-0-0-10-0-2-updated-on-june-13/7911
- ✅  Update from 10.0.1 to 10.0.2 via CLI

@VicDeo Please Merge
@crrodriguez Please deploy after merging

**Comment by VicDeo** [comment]
merged
@crrodriguez please deploy

**Comment by crrodriguez** [comment]
@VicDeo done

**Pull request merged**
