### PR TITLE
Release 10.2 on beta and daily channels

### PR DESCRIPTION
**Pull request by VicDeo**
Unlock 10.2 on beta and daily channels.
Remove duplicated and irrelevant test cases for the daily channel

### CODE REVIEW

**Comment by davitol** [comment]
Testing the  PR using oC 10.1.1 to stable10 i got:

```
Forbidden

You don't have permission to access /apps/files/ on this server.
```

Not sure if you tested it too and happens or it is related to my environment @VicDeo

**Comment by davitol** [comment]
Testing the PR using oC 10.1.0 to 10.2 went fine

**Comment by VicDeo** [comment]
@davitol there should be no difference for 10.1.0 and 10.1.1 - both get 10.2.0 as the available OC version.
AFAIK 10.1.1 is a 10.1.0 with one small patch on top of it

**Comment by patrickjahns** [comment]
@VicDeo 
Shouldn't this also go to the stable channel?

**Comment by VicDeo** [comment]
@crrodriguez please deploy

**Comment by VicDeo** [comment]
@patrickjahns yes, but a bit later

**Comment by crrodriguez** [comment]
done

**Pull request merged**
