### PR TITLE
Allow 9.0.x to 9.0.8

### PR DESCRIPTION
**Pull request by VicDeo**
Unlock update to 9.0.8 for  9.0.x

### CODE REVIEW

**Comment by davitol** [comment]
:+1: Tested and works
- ✅  906 encrypted to 908 via stable channel WebUI
- ✅  907 encrypted to 908 via stable channel CLI

After the updates, it was done a sanity test related to login, shares kept available, users created, etc...

**Comment by davitol** [comment]
Testing this PR I missed this stuff in daily:

```
	'daily' => [
3 months ago @PVince81 Make update server public 	
		'9.2' => [
			'downloadUrl' => 'https://download.owncloud.org/community/owncloud-daily-master.zip',
			'web' => 'https://doc.owncloud.org/server/9.2/admin_manual/maintenance/upgrade.html',
```
I guess it should be 10.0 oC version instead of 9.2. @VicDeo

**Comment by PVince81** [comment]
yes, 10.0. should we revert ?

**Comment by davitol** [comment]
@VicDeo Due to the PR only affects to 9.0.x to 9.0.8 and to 9.1.X. , does it affects that 9.2 URL in daily or maybe it is only needed to fix it in the https://github.com/owncloud/administration/pull/111 PR? Thanks in advanced

**Comment by VicDeo** [comment]
@davitol 9.0.x to 9.0.8 only, not any other kind.

**Pull request merged**
