### PR TITLE
Allow 10.0.x to 10.0.3 all channels, 9.1.6 to 10.0.3 at stable

### PR DESCRIPTION
**Pull request by VicDeo**
- [x] 9.0.10 to 9.1.6 at `stable` channel
- [x] 9.1.6 to 10.0.3 at `stable` channel
- [x] 10.0.x to 10.0.3 for all channels except `daily` 
`daily` channel as usual allows 10.0.x  to master

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 so, what about 9.0 to 9.1 at `stable`? Will we allow this too?
cc @hodyroff

**Comment by PVince81** [comment]
> so, what about 9.0 to 9.1 at stable? Will we allow this too?

@VicDeo yeah, let's do that too to encourage upgrading to 10.0.3

**Comment by PVince81** [comment]
@VicDeo @davitol can we test and deploy this ?

**Comment by davitol** [comment]
Related issue:
https://github.com/owncloud/updater/issues/442

**Comment by davitol** [comment]
- [x] 9.1.6 to 10.0.3 at `stable` channel
- [x] 10.0.x to 10.0.3 for all channels except `daily` 
`daily` channel as usual allows 10.0.x  to master

Tested and works. 

Known issues:
- We have to patch our server with the PR that fits if we stumble upon this issue:
https://github.com/owncloud/updater/issues/414
- This known issue was reproduced too: https://github.com/owncloud/updater/issues/436

**Comment by PVince81** [comment]
> Also we have to take into account that encryption gets disable after updating from 10.0.1 to 10.0.3 and admin has to reenable it

@davitol is it really disabled ? On my instance (not updated with updater but with distro package), while the UI looked like encryption mode has not be selected, it still works with user-keys.

**Comment by davitol** [comment]
> @davitol is it really disabled ? On my instance (not updated with updater but with distro package), while the UI looked like encryption mode has not be selected, it still works with user-keys.

Yes, after updating it appears disabled:

screen shot 2017-09-22 at 13 54 00

screen shot 2017-09-22 at 13 52 19


So if admin doesn't enable the module again, the file is not accesible for the user

screen shot 2017-09-22 at 13 53 18

**Comment by VicDeo** [comment]
@davitol 
yes, like you reported before https://github.com/owncloud/updater/issues/428 unfortunately the fix doesn't work backwards

**Comment by PVince81** [comment]
If not fixable we need a good way to communicate this. Sadly we can't display messages in the updater like the release notes.

**Comment by davitol** [comment]
👍  QA is finished so @VicDeo @PVince81 How to go on with the "buggy" scenarios above.

**Comment by VicDeo** [comment]
Scenarios are covered in https://central.owncloud.org/t/10-0-3-notes-on-using-built-in-web-updater/9702
Let's the battle begin :kimono:

**Comment by VicDeo** [comment]
@crrodriguez this one please ;)

**Comment by crrodriguez** [comment]
@VicDeo done

**Comment by PVince81** [comment]
@VicDeo can we add the encryption bit to the release notes too ? https://doc.owncloud.org/server/latest/admin_manual/release_notes.html

**Pull request merged**
