### PR TITLE
Push 10.0.2, 9.1.6, 9.0.10 to all channels

### PR DESCRIPTION
**Pull request by VicDeo**

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 @davitol

**Comment by PVince81** [comment]
To be deployed at least 24 hours after the tarballs are announced.

Still, take the time to test these.

**Comment by PVince81** [comment]
@SergioBertolinSG please test (@davitol is out for a few days)

**Comment by davitol** [comment]
**QA results**

**WebUI**

- [ ] Update from 9.0.8 to 9.0.10 via stable channel
- [ ] Update from 9.1.5 to 9.1.6 via stable channel
- [ ] Update from 9.1.6 to 10.0.2 via stable channel

- [ ] Update from 9.0.10 to 9.1.6 via daily channel
- [ ] Update from 9.1.6 to 10.0.2 via daily channel

**CLI**

- [ ] Update from 9.0.8 to 9.0.10 via stable channel
- [ ] Update from 9.1.5 to 9.1.6 via stable channel
- [ ] Update from 9.1.6 to 10.0.2 via stable channel

- [ ] Update from 9.0.10 to 9.1.6 via daily channel
- [ ] Update from 9.1.6 to 10.0.2 via daily channel

**Comment by davitol** [comment]
https://github.com/owncloud/administration/pull/130 Splitted, let's close this PR

**Pull request closed without merging**
