### PR TITLE
Push 10.0.6 to beta channel

### PR DESCRIPTION
**Pull request by VicDeo**
https://github.com/owncloud/core/issues/30298

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 @davitol

**Comment by davitol** [comment]
✅ 10.0.4 -> 10.0.6
✅ 9.1.7 --> 10.0.6

**Comment by davitol** [comment]
👍

**Comment by PVince81** [comment]
How about we do the stable channel as well now ?

**Comment by VicDeo** [comment]
@PVince81 ok

**Comment by VicDeo** [comment]
https://github.com/owncloud/administration/pull/147

**Pull request merged**
