### PR TITLE
[Update server] Push 8.2.11 9.0.9 9.1.5  to the stable/production cha…

### PR DESCRIPTION
**Pull request by VicDeo**
…nnels

### CODE REVIEW

**Comment by davitol** [comment]
@VicDeo 
```
		'9.2' => [
 			'downloadUrl' => 'https://download.owncloud.org/community/owncloud-daily-master.zip',
 			'web' => 'https://doc.owncloud.org/server/10.0/admin_manual/maintenance/upgrade.html',
		],
```
I guess this should be remove from the config.php file

**Comment by VicDeo** [comment]
@davitol '9.2' for daily channel only. For those who are used early dailies.

**Comment by davitol** [comment]
👍 Tested and works. @crrodriguez Please deploy

**Comment by crrodriguez** [comment]
long ago deployed, please close.

**Comment by davitol** [comment]
> long ago deployed, please close.

@crrodriguez close which ticket?

**Pull request merged**
