### PR TITLE
Allow update to 10.0.1RC3 via beta channel

### PR DESCRIPTION
**Pull request by VicDeo**
...for testing

### CODE REVIEW

**Comment by PVince81** [comment]
Please post the scenarios you manually tested, thanks. Else I'll assume you didn't test it.

**Comment by VicDeo** [comment]
@PVince81 `beta` channel is intended for testing https://owncloud.org/release-channels/
>Beta
Betas and release candidates are the versions of choice for testers in preparation for an ownCloud release. They provide a short-term-stable point to report bugs against. Grab these to make sure the upcoming release works well on your infrastructure.
Automatically generated snapshot tarballs and packages track daily ownCloud development. These are suitable to check if bugs are fixed but can break any time.

The only test I did is that an URL allows to download the package

**Comment by PVince81** [comment]
Please test updating from 9.1.5 to beta / 10.0.1RC3 with the web updater to confirm there aren't other hidden issues. If integrity check passes and uploading a file works then we're fine.

**Comment by VicDeo** [comment]
outdated

**Pull request closed without merging**
