### PR TITLE
Push 10.0.4beta2 to beta channel

### PR DESCRIPTION
**Pull request by VicDeo**
To test
- [x] update 10.0.3 -> 10.0.4beta2
- [x] update 9.1.6 -> 10.0.4beta2

### CODE REVIEW

**Comment by davitol** [comment]
@VicDeo 

update 10.0.3 -> 10.0.4beta2

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 1e07f977eea4bc3ffde4c42128df9a0e6ff1153d1f28ab0dbea952b39565b72f62b20c1b94f64c261e2484e47442258563357c18406a58a6819d298aed8800d1
                            [current] => 
                        )

                )

        )

)

```

**Comment by PVince81** [comment]
@davitol known issue, please ignore.

It should be fixed in daily already now, it was a bug with the release script.

**Comment by davitol** [comment]
@PVince81 @VicDeo from 9.1.6 

```
- core
	- FILE_MISSING
		- CHANGELOG.md
		- core/js/mimetypelist.js
```

That CHANGELOG.md warning is already known too?

**Comment by PVince81** [comment]
@davitol if you upgraded from 9.1 then you'd get the CHANGELOG. The bug is in the 9.1 updater so one needs to patch it: https://central.owncloud.org/t/10-0-3-notes-on-using-built-in-web-updater/9702

**Comment by PVince81** [comment]
@crrodriguez please deploy

**Comment by crrodriguez** [comment]
@PVince81 done

**Pull request merged**
